import { watch } from 'node:fs';
import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { dirname, join, relative, resolve, sep } from 'node:path';
import { compileComponentParts } from './index.js';

export interface ProjectStyles {
  cssOutputPath?: string;
}

async function filesInDirectory(
  directory: string,
  include: (filename: string) => boolean,
  prefix = '',
): Promise<string[]> {
  const entries = await readdir(join(directory, prefix), {
    withFileTypes: true,
  });
  const paths = await Promise.all(
    entries.map(async (entry) => {
      const path = join(prefix, entry.name);
      if (entry.isDirectory())
        return filesInDirectory(directory, include, path);
      return entry.isFile() && include(entry.name) ? [path] : [];
    }),
  );
  return paths.flat().sort();
}

function generatedPath(viewPath: string): string {
  return `${viewPath.slice(0, -'.workstar'.length)}.ts`;
}

function relocatedImport(
  sourcePath: string,
  outputPath: string,
  specifier: string,
): string {
  const target = resolve(dirname(sourcePath), specifier);
  const path = relative(dirname(outputPath), target).split(sep).join('/');
  return path.startsWith('.') ? path : `./${path}`;
}

/** Compile one authored view without rewriting unrelated generated modules. */
export async function compileViewFile(
  sourcePath: string,
  outputPath: string,
  options: ProjectStyles = {},
): Promise<void> {
  const source = await readFile(sourcePath, 'utf8');
  const { code, css } = compileComponentParts(source, sourcePath, {
    rewriteRelativeImport: (specifier) =>
      relocatedImport(sourcePath, outputPath, specifier),
  });
  if (css && !options.cssOutputPath) {
    throw new Error(
      `${sourcePath}: pass cssOutputPath to emit component styles.`,
    );
  }
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, code, 'utf8');
  if (options.cssOutputPath) {
    await mkdir(dirname(options.cssOutputPath), { recursive: true });
    await writeFile(options.cssOutputPath, css, 'utf8');
  }
}

/** Compile every view before writing any generated modules. */
export async function compileViewDirectory(
  sourceDirectory: string,
  outputDirectory: string,
  options: ProjectStyles = {},
): Promise<string[]> {
  const viewPaths = await filesInDirectory(sourceDirectory, (name) =>
    name.endsWith('.workstar'),
  );
  if (viewPaths.length === 0) {
    throw new Error(`No .workstar views found in ${sourceDirectory}.`);
  }

  const modules = await Promise.all(
    viewPaths.map(async (viewPath) => {
      const sourcePath = join(sourceDirectory, viewPath);
      const outputPath = join(outputDirectory, generatedPath(viewPath));
      const source = await readFile(sourcePath, 'utf8');
      const { code, css } = compileComponentParts(source, sourcePath, {
        rewriteRelativeImport: (specifier) =>
          relocatedImport(sourcePath, outputPath, specifier),
      });
      return {
        filename: generatedPath(viewPath),
        code,
        css,
      };
    }),
  );

  if (modules.some(({ css }) => css) && !options.cssOutputPath) {
    throw new Error('Pass cssOutputPath to emit component styles.');
  }

  await mkdir(outputDirectory, { recursive: true });
  const current = new Set(modules.map(({ filename }) => filename));
  for (const path of await filesInDirectory(outputDirectory, (name) =>
    name.endsWith('.ts'),
  )) {
    if (current.has(path)) continue;
    const stalePath = join(outputDirectory, path);
    if (
      (await readFile(stalePath, 'utf8')).startsWith(
        '// Generated by workstar-compiler.',
      )
    ) {
      await rm(stalePath);
    }
  }
  await Promise.all(
    modules.map(async ({ filename, code }) => {
      const outputPath = join(outputDirectory, filename);
      await mkdir(dirname(outputPath), { recursive: true });
      await writeFile(outputPath, code, 'utf8');
    }),
  );
  if (options.cssOutputPath) {
    const stylesheet = modules
      .filter(({ css }) => css)
      .map(({ filename, css }) => `/* ${filename} */\n${css}`)
      .join('\n');
    await mkdir(dirname(options.cssOutputPath), { recursive: true });
    await writeFile(options.cssOutputPath, stylesheet, 'utf8');
  }
  return modules.map(({ filename }) => filename);
}

/** Watch a view directory and recompile changed views for local development. */
export async function watchViewDirectory(
  sourceDirectory: string,
  outputDirectory: string,
  onError: (error: unknown) => void,
  options: ProjectStyles = {},
): Promise<() => void> {
  await compileViewDirectory(sourceDirectory, outputDirectory, options);
  let debounce: ReturnType<typeof setTimeout> | undefined;
  let compiling = false;
  let pending = false;

  async function recompile(): Promise<void> {
    if (compiling) {
      pending = true;
      return;
    }
    compiling = true;
    do {
      pending = false;
      try {
        await compileViewDirectory(sourceDirectory, outputDirectory, options);
      } catch (error) {
        onError(error);
      }
    } while (pending);
    compiling = false;
  }

  const watcher = watch(
    sourceDirectory,
    { recursive: true },
    (_event, filename) => {
      if (filename && !filename.endsWith('.workstar')) return;
      if (debounce) clearTimeout(debounce);
      debounce = setTimeout(() => void recompile(), 60);
    },
  );
  return () => {
    if (debounce) clearTimeout(debounce);
    watcher.close();
  };
}
