import {
  mkdir,
  mkdtemp,
  readFile,
  readdir,
  rm,
  writeFile,
} from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it, vi } from 'vitest';
import { compileViewDirectory, watchViewDirectory } from '../src/project.js';

describe('view directory compilation', () => {
  it('emits deterministic CSS for SSR and fails instead of silently dropping styles', async () => {
    const temporary = await mkdtemp(join(tmpdir(), 'workstar-styles-'));
    const output = join(temporary, 'generated');
    const stylesheet = join(temporary, 'public', 'components.css');
    try {
      await writeFile(
        join(temporary, 'home.workstar'),
        '<main class="card">Hello</main><style>.card { color: red }</style>',
      );
      await expect(compileViewDirectory(temporary, output)).rejects.toThrow(
        'Pass cssOutputPath',
      );
      await expect(readdir(output)).rejects.toMatchObject({ code: 'ENOENT' });
      await compileViewDirectory(temporary, output, {
        cssOutputPath: stylesheet,
      });
      expect(await readFile(stylesheet, 'utf8')).toMatch(
        /\.card:where\(\[data-workstar-[a-f0-9]{10}\]\)/,
      );
      await writeFile(join(temporary, 'home.workstar'), '<main>Hello</main>');
      await compileViewDirectory(temporary, output, {
        cssOutputPath: stylesheet,
      });
      expect(await readFile(stylesheet, 'utf8')).toBe('');
    } finally {
      await rm(temporary, { recursive: true, force: true });
    }
  });

  it('generates typed modules in deterministic order', async () => {
    const temporary = await mkdtemp(join(tmpdir(), 'workstar-views-'));
    const output = join(temporary, 'generated');
    try {
      await writeFile(
        join(temporary, 'b.workstar'),
        '<script lang="ts">export interface Props { name: string }</script><p>{name}</p>',
      );
      await writeFile(
        join(temporary, 'a.workstar'),
        '<script lang="ts">export interface Props {}</script><p>Hello</p>',
      );
      await writeFile(join(temporary, 'notes.txt'), 'not a view');

      expect(await compileViewDirectory(temporary, output)).toEqual([
        'a.ts',
        'b.ts',
      ]);
      expect(await readdir(output)).toEqual(['a.ts', 'b.ts']);
      expect(await readFile(join(output, 'b.ts'), 'utf8')).toContain(
        'Generated by workstar-compiler',
      );
    } finally {
      await rm(temporary, { recursive: true, force: true });
    }
  });

  it('does not write partial output when any view is invalid', async () => {
    const temporary = await mkdtemp(join(tmpdir(), 'workstar-views-'));
    const output = join(temporary, 'generated');
    try {
      await writeFile(
        join(temporary, 'a.workstar'),
        '<script lang="ts">export interface Props {}</script><p>valid</p>',
      );
      await writeFile(
        join(temporary, 'b.workstar'),
        '<script lang="js">export interface Props {}</script><p>invalid</p>',
      );
      await expect(compileViewDirectory(temporary, output)).rejects.toThrow(
        'The component script must be <script lang="ts">.',
      );
      await expect(readdir(output)).rejects.toMatchObject({ code: 'ENOENT' });
    } finally {
      await rm(temporary, { recursive: true, force: true });
    }
  });

  it('reports the authored file and position from a project build', async () => {
    const temporary = await mkdtemp(join(tmpdir(), 'workstar-diagnostics-'));
    const source = join(temporary, 'src');
    const output = join(temporary, 'generated');
    try {
      await mkdir(source);
      const view = join(source, 'contact.workstar');
      await writeFile(
        view,
        '<If when={ready}>\n  <a onclick="alert(1)">Bad</a>\n</If>',
      );
      await expect(compileViewDirectory(source, output)).rejects.toThrow(
        `${view}:2:3: Use on:event instead of onclick.`,
      );
      await expect(readdir(output)).rejects.toMatchObject({ code: 'ENOENT' });
    } finally {
      await rm(temporary, { recursive: true, force: true });
    }
  });

  it('mirrors nested views and cleans only obsolete generated modules', async () => {
    const temporary = await mkdtemp(join(tmpdir(), 'workstar-views-'));
    const source = join(temporary, 'ui');
    const output = join(temporary, 'generated');
    try {
      await mkdir(join(source, 'pages'), { recursive: true });
      await mkdir(join(source, 'shared'), { recursive: true });
      await writeFile(join(source, 'pages', 'home.workstar'), '<h1>Home</h1>');
      await writeFile(join(source, 'shared', 'card.workstar'), '<p>Card</p>');
      expect(await compileViewDirectory(source, output)).toEqual([
        join('pages', 'home.ts'),
        join('shared', 'card.ts'),
      ]);
      expect(
        await readFile(join(output, 'pages', 'home.ts'), 'utf8'),
      ).toContain('<h1>Home</h1>');
      await writeFile(
        join(output, 'shared', 'manual.ts'),
        'export const manual = true;',
      );
      await rm(join(source, 'shared', 'card.workstar'));
      await compileViewDirectory(source, output);
      expect(await readdir(join(output, 'shared'))).toEqual(['manual.ts']);
    } finally {
      await rm(temporary, { recursive: true, force: true });
    }
  });

  it('preserves relative TypeScript imports when output is outside src', async () => {
    const temporary = await mkdtemp(join(tmpdir(), 'workstar-imports-'));
    const source = join(temporary, 'src', 'views');
    const output = join(temporary, '.workstar', 'generated');
    try {
      await mkdir(source, { recursive: true });
      await writeFile(
        join(source, 'page.workstar'),
        `<script lang="ts">
import type { PageCopy } from '../content';
import Card from './card.workstar';
export interface Props { copy: PageCopy }
</script><Use component={Card} />`,
      );
      await writeFile(join(source, 'card.workstar'), '<p>Card</p>');
      await compileViewDirectory(source, output);
      const page = await readFile(join(output, 'page.ts'), 'utf8');
      expect(page).toContain('from "../../src/content"');
      expect(page).toContain("from './card'");
    } finally {
      await rm(temporary, { recursive: true, force: true });
    }
  });

  it('removes obsolete generated views but preserves other files', async () => {
    const temporary = await mkdtemp(join(tmpdir(), 'workstar-views-'));
    const output = join(temporary, 'generated');
    try {
      await writeFile(
        join(temporary, 'old.workstar'),
        '<script lang="ts">export interface Props {}</script><p>Old</p>',
      );
      await compileViewDirectory(temporary, output);
      await rm(join(temporary, 'old.workstar'));
      await writeFile(
        join(temporary, 'current.workstar'),
        '<script lang="ts">export interface Props {}</script><p>Current</p>',
      );
      await writeFile(join(output, 'manual.ts'), 'export const manual = true;');
      await compileViewDirectory(temporary, output);
      expect(await readdir(output)).toEqual(['current.ts', 'manual.ts']);
    } finally {
      await rm(temporary, { recursive: true, force: true });
    }
  });

  it('recompiles edited views while watching', async () => {
    const temporary = await mkdtemp(join(tmpdir(), 'workstar-views-'));
    const output = join(temporary, 'generated');
    const view = join(temporary, 'page.workstar');
    let stop: (() => void) | undefined;
    const errors: unknown[] = [];
    try {
      await writeFile(
        view,
        '<script lang="ts">export interface Props {}</script><p>Before</p>',
      );
      stop = await watchViewDirectory(temporary, output, (error) =>
        errors.push(error),
      );
      await writeFile(
        view,
        '<script lang="ts">export interface Props {}</script><p>After</p>',
      );
      await vi.waitFor(
        async () => {
          expect(await readFile(join(output, 'page.ts'), 'utf8')).toContain(
            'After',
          );
        },
        { timeout: 3000 },
      );
      expect(errors).toEqual([]);
    } finally {
      stop?.();
      await rm(temporary, { recursive: true, force: true });
    }
  });

  it('watches edits inside nested view directories', async () => {
    const temporary = await mkdtemp(join(tmpdir(), 'workstar-views-'));
    const source = join(temporary, 'components');
    const output = join(temporary, 'generated');
    const view = join(source, 'pages', 'home.workstar');
    let stop: (() => void) | undefined;
    const errors: unknown[] = [];
    try {
      await mkdir(join(source, 'pages'), { recursive: true });
      await writeFile(view, '<h1>Before</h1>');
      stop = await watchViewDirectory(source, output, (error) =>
        errors.push(error),
      );
      await writeFile(view, '<h1>After</h1>');
      await vi.waitFor(
        async () => {
          expect(
            await readFile(join(output, 'pages', 'home.ts'), 'utf8'),
          ).toContain('After');
        },
        { timeout: 3000 },
      );
      expect(errors).toEqual([]);
    } finally {
      stop?.();
      await rm(temporary, { recursive: true, force: true });
    }
  });

  it('watches views in directories created after watching starts', async () => {
    const temporary = await mkdtemp(join(tmpdir(), 'workstar-views-'));
    const source = join(temporary, 'src');
    const output = join(temporary, '.workstar', 'generated');
    let stop: (() => void) | undefined;
    const errors: unknown[] = [];
    try {
      await mkdir(source);
      await writeFile(join(source, 'home.workstar'), '<h1>Home</h1>');
      stop = await watchViewDirectory(source, output, (error) =>
        errors.push(error),
      );

      const newDirectory = join(source, 'features', 'contact');
      await mkdir(newDirectory, { recursive: true });
      await writeFile(
        join(newDirectory, 'form.workstar'),
        '<form>Contact</form>',
      );

      await vi.waitFor(
        async () => {
          expect(
            await readFile(
              join(output, 'features', 'contact', 'form.ts'),
              'utf8',
            ),
          ).toContain('<form>Contact</form>');
        },
        { timeout: 3000 },
      );
      expect(errors).toEqual([]);
    } finally {
      stop?.();
      await rm(temporary, { recursive: true, force: true });
    }
  });
});
